#!/bin/bash
set -euo pipefail
# =========================================================
# 說明：
# 1. 掃描 /srv 下 services 目錄內的 /log/access.log 與 /log/error.log
# 2. 自動產生 logrotate 設定檔
# 3. 可重複執行，每次都會依目前檔案現況重建設定
# 4. 建立後進行 debug 模擬檢查（不實際執行輪換）
# =========================================================

LOGROTATE_FILE="/etc/logrotate.d/srv-services-web-logs"
TMP_FILE="$(mktemp)"

# ── ANSI 色碼 ──────────────────────────────────────────
RESET='\033[0m'
BOLD='\033[1m'
DIM='\033[2m'
C_BLUE='\033[38;5;111m'
C_CYAN='\033[38;5;116m'
C_GREEN='\033[38;5;114m'
C_YELLOW='\033[38;5;222m'
C_PURPLE='\033[38;5;183m'
C_GRAY='\033[38;5;245m'
C_WHITE='\033[38;5;253m'

# ── 輸出函式 ───────────────────────────────────────────
print_header() {
    echo
    echo -e "${C_BLUE}${BOLD}╔══════════════════════════════════════════════════════╗${RESET}"
    echo -e "${C_BLUE}${BOLD}║${RESET}  ${C_PURPLE}${BOLD}logrotate 設定同步工具${RESET}  ${C_GRAY}$(basename "$0")${RESET}  ${C_BLUE}${BOLD}                ║${RESET}"
    echo -e "${C_BLUE}${BOLD}╚══════════════════════════════════════════════════════╝${RESET}"
    echo
}

print_step() {
    echo -e "${C_GREEN}▶${RESET} ${BOLD}${C_WHITE}$1${RESET}  ${DIM}${C_GRAY}$2${RESET}"
}

print_ok() {
    echo -e "  ${C_GREEN}✔${RESET} ${C_GREEN}$1${RESET}  ${DIM}${C_GRAY}$2${RESET}"
}

print_warn() {
    echo -e "  ${C_YELLOW}⚠${RESET}  ${C_YELLOW}$1${RESET}"
}

print_item_tree() {
    local files=("$@")
    local count="${#files[@]}"
    for i in "${!files[@]}"; do
        local f="${files[$i]}"
        local size
        size=$(du -sh "$f" 2>/dev/null | cut -f1)
        if [[ $((i + 1)) -eq $count ]]; then
            echo -e "  ${C_GRAY}└─${RESET} ${C_YELLOW}${f}${RESET}  ${C_GREEN}${size}${RESET}"
        else
            echo -e "  ${C_GRAY}├─${RESET} ${C_YELLOW}${f}${RESET}  ${C_GREEN}${size}${RESET}"
        fi
    done
}

print_divider() {
    echo -e "${C_BLUE}${DIM}───────────────────────────────────────────────────────${RESET}"
}

print_footer() {
    print_divider
    echo -e "${C_GREEN}${BOLD}✔ 完成${RESET}  ${C_GRAY}$(date '+%F %T %z')${RESET}"
    echo
    echo -e "  ${C_GRAY}實際輪換將由 ${C_CYAN}/etc/cron.daily/logrotate${C_GRAY} 依條件自動執行${RESET}"
    echo -e "  ${C_GRAY}可重複執行，無副作用${RESET}"
    echo
}

cleanup() {
    rm -f "$TMP_FILE"
}
trap cleanup EXIT

# ── 主流程 ─────────────────────────────────────────────
print_header

# Step 1：掃描
print_step "掃描 log 檔案" "/srv/**/services/*/log/"
echo

find /srv -type f \( \
    -path "*/services/*/log/access.log" -o \
    -path "*/services/*/log/error.log" \
\) 2>/dev/null | sort > "$TMP_FILE"

if [[ ! -s "$TMP_FILE" ]]; then
    print_warn "找不到任何符合條件的 log 檔案，結束。"
    echo
    exit 0
fi

# 讀入陣列以便顯示 tree 與計數
mapfile -t LOG_FILES < "$TMP_FILE"
FILE_COUNT="${#LOG_FILES[@]}"

echo -e "  ${C_CYAN}找到 ${BOLD}${FILE_COUNT}${RESET}${C_CYAN} 個 log 檔案：${RESET}"
print_item_tree "${LOG_FILES[@]}"
echo

# Step 2：產生設定檔
print_step "產生設定檔" "$LOGROTATE_FILE"

{
    echo "# Auto generated by $(basename "$0")"
    echo "# Generated at: $(date '+%F %T %z')"
    echo ""
    while IFS= read -r file; do
        cat <<EOF
"$file" {
    daily
    size 10M
    rotate 7
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
    su root root
}

EOF
    done < "$TMP_FILE"
} > "$LOGROTATE_FILE"

chmod 644 "$LOGROTATE_FILE"
print_ok "已寫入，共 ${FILE_COUNT} 個區塊" "(chmod 644)"
echo

# Step 3：顯示內容（可選，折疊顯示）
echo -e "  ${DIM}${C_GRAY}--- 設定預覽 ---${RESET}"
sed 's/^/  /' "$LOGROTATE_FILE" | grep --color=never '' | \
    awk '{printf "\033[2m\033[38;5;245m%s\033[0m\n", $0}'
echo

# Step 4：Debug 模擬
print_step "Debug 模擬" "logrotate -d /etc/logrotate.conf"
echo

LOGROTATE_DEBUG_OUT="$(logrotate -d /etc/logrotate.conf 2>&1)"
LOGROTATE_EXIT=$?

# 只顯示錯誤/警告行，過濾掉 verbose 雜訊
ERRORS=$(echo "$LOGROTATE_DEBUG_OUT" | grep -iE "error|warning" || true)

if [[ $LOGROTATE_EXIT -eq 0 && -z "$ERRORS" ]]; then
    print_ok "設定檢查通過，無錯誤" ""
elif [[ -n "$ERRORS" ]]; then
    while IFS= read -r line; do
        print_warn "$line"
    done <<< "$ERRORS"
else
    print_ok "設定檢查完成" "(exit ${LOGROTATE_EXIT})"
fi
echo

print_footer
